export const itemDetailSchema = {
  type: "object",
  properties: {
    id: { type: "string" },
    name: { type: "string" },
    rarityTierLevel: { type: "number", enum: [1, 2, 3] },
    textureUrl: { type: ["string", "null"] },
    baseValueCents: { type: "number" },
    currentValueCents: { type: "number", description: "Live simulated value — ticks every 30s, see PRD §28" },
    minValueCents: { type: "number" },
    maxValueCents: { type: "number" },
    category: { type: "string" },
    collection: { type: ["string", "null"] },
    tagline: { type: ["string", "null"] },
    traits: { type: ["string", "null"] },
    pokemonName: { type: ["string", "null"] },
    cardTitle: { type: ["string", "null"] },
    pokemonType: { type: ["string", "null"] },
    generation: { type: ["string", "null"] },
    pokedexNumber: { type: ["string", "null"] },
    watchName: { type: ["string", "null"] },
    modelName: { type: ["string", "null"] },
    brand: { type: ["string", "null"] },
    style: { type: ["string", "null"] },
    caseMaterial: { type: ["string", "null"] },
    dialColor: { type: ["string", "null"] },
    movement: { type: ["string", "null"] },
    caseSize: { type: ["string", "null"] },
  },
};
